[package]
name = "rchat"
version = "0.1.0"
authors = ["1amL0st <dyomin.dyominalexander2011@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-files = "0.5.0"
actix = "0.10"